Numpy    20/6/23

In [35]:
import numpy as np

filling arrays with auto elements

In [36]:
import numpy as np

arr =  np.zeros(4)
print(arr)                  #return value is lidt

[0. 0. 0. 0.]


In [37]:
arr=np.ones((4,2))    #tuple
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [38]:
arr=np.arange(10,21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


In [39]:
arr=np.arange(4)
print(arr)

[0 1 2 3]


In [40]:
arr=np.arange(2,14,2)
print(arr)

[ 2  4  6  8 10 12]


sorting array

In [41]:
arr=np.array([2,1,5,3,7,4,7,6,8])

print(np.sort(arr))

[1 2 3 4 5 6 7 7 8]


In [42]:
arr=np.array(['apple','pineapple','banana','strawberry'])
print(np.sort(arr))

['apple' 'banana' 'pineapple' 'strawberry']


21/6/23

In [43]:
arr = np.array([-5,65,70,-7550,20,300,30])

print(arr[0:2])

[-5 65]


In [44]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43]])
print(mat)
print(mat[1,1])
print(mat[0,4])

[[10 20 21 22 25]
 [30 40 41 42 43]]
40
25


In [45]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43],[12,13,14,15,43]])
print(mat[0,1])
print(mat[1:3])

20
[[30 40 41 42 43]
 [12 13 14 15 43]]


In [46]:
mat=np.array([  [[21,22,23],[24,25,26]] , [[34,35,36],[31,32,33]] ] )        #3Dimensional
print(mat)
print("value:",mat[1,0,0])
print("value:",mat[1,1,0])
print(mat[1,1,1:3])

[[[21 22 23]
  [24 25 26]]

 [[34 35 36]
  [31 32 33]]]
value: 34
value: 31
[32 33]


In [47]:
arr=np.array([1,2,3,4,5,6])

print(arr[1:5:2])

[2 4]


In [48]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


Searching in array

numpy.where()
<>
numpy.searchsorted()

In [49]:
arr=np.array([1,2,3,4,5,6,7,8])

val=np.where(arr%4==0)
print(val)


(array([3, 7], dtype=int64),)


In [50]:
arr=np.array([2,50,23,60,56,80])

val=np.where(arr%10==0)
print(val)

(array([1, 3, 5], dtype=int64),)


In [51]:
arr=np.array([0.4,0.5,0.7,0.8,0.9])

val=np.where(arr==0.7)
print(val)

(array([2], dtype=int64),)


In [52]:
arr=np.array(["'a'",'b','c','d','e','f'])

val=np.where(arr=='d')

print(val)

(array([3], dtype=int64),)


In [53]:
arr=np.array([6,7,9,19])
x=np.searchsorted(arr,8)
print(x)

2


In [54]:
arr=np.searchsorted([1,2,3,4,5],3)  #inserting 3 in the array
arr

2

In [55]:
arr=np.searchsorted([1,2,3,4,5],3,side='right')
arr

3

In [56]:
arr=np.searchsorted([1,2,3,4,5],[-10,10,2,3])
arr

array([0, 5, 1, 2], dtype=int64)

In [57]:
arr=np.searchsorted([1,3,5,2,8],4)
arr


2

In [58]:
arr=np.array([1,20,30,45,58])
val=np.searchsorted(arr,[-10,40,55])
val

array([0, 3, 4], dtype=int64)

reshapping Array: reshape()

In [59]:
arr=np.array([[23,24,35,11,13,24,24,54,56,67,87,89]])
rs=arr.reshape(4,3)      #4 rows 3 columns
rs

array([[23, 24, 35],
       [11, 13, 24],
       [24, 54, 56],
       [67, 87, 89]])

In [60]:
arr=np.array([[1,2],[3,4]])
rs=arr.reshape(-1)         #converting 2D into 1D
rs

array([1, 2, 3, 4])

In [61]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[1,2,3]]])
rs=arr.reshape(-1)
rs

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 1, 2, 3])

Filtering Array : filter()

In [62]:
# checking numpy version
import numpy as np
print(np.version)



<module 'numpy.version' from 'c:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\version.py'>


In [63]:
arr= np.array(42)
arr

array(42)

In [64]:
np.zeros(2)

array([0., 0.])

In [65]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,])
arr[1:5:2]

array([2, 4])