Numpy   20/6/23

In [3]:
import numpy as np 


filling arrays  with auto elements

In [4]:
import numpy as np

arr = np.zeros(4)
print(arr)                  #return value is lidt

[0. 0. 0. 0.]


In [5]:
arr=np.ones((4,2))    #tuple
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
arr=np.arange(10,21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


In [7]:
arr=np.arange(4)
print(arr)

[0 1 2 3]


In [8]:
arr=np.arange(2,14,2)
print(arr)

[ 2  4  6  8 10 12]


sorting array

In [9]:
arr=np.array([2,1,5,3,7,4,7,6,8])

print(np.sort(arr))

[1 2 3 4 5 6 7 7 8]


In [10]:
arr=np.array(['apple','pineapple','banana','strawberry'])
print(np.sort(arr))

['apple' 'banana' 'pineapple' 'strawberry']


21/6/23

In [11]:
arr = np.array([-5,65,70,-7550,20,300,30])

print(arr[0:2])

[-5 65]


In [14]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43]])
print(mat)
print(mat[1,1])
print(mat[0,4])

[[10 20 21 22 25]
 [30 40 41 42 43]]
40
25


In [28]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43],[12,13,14,15,43]])
print(mat[0,1])
print(mat[1:3])

20
[[30 40 41 42 43]
 [12 13 14 15 43]]


In [30]:
mat=np.array([  [[21,22,23],[24,25,26]] , [[34,35,36],[31,32,33]] ] )        #3Dimensional
print(mat)
print("value:",mat[1,0,0])
print("value:",mat[1,1,0])

[[[21 22 23]
  [24 25 26]]

 [[34 35 36]
  [31 32 33]]]
value: 34
value: 31
