Numpy   20/6/23

In [79]:
import numpy as np 


filling arrays with auto elements

In [80]:
import numpy as np

arr =  np.zeros(4)
print(arr)                  #return value is lidt

[0. 0. 0. 0.]


In [81]:
arr=np.ones((4,2))    #tuple
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [82]:
arr=np.arange(10,21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


In [83]:
arr=np.arange(4)
print(arr)

[0  1 2 3]


In [84]:
arr=np.arange(2,14,2)
print(arr)

[ 2  4  6  8 10 12]


sorting array

In [85]:
arr=np.array([2,1,5,3,7,4,7,6,8])

print(np.sort(arr))

[1 2 3 4 5 6 7 7 8]


In [86]:
arr=np.array(['apple','pineapple','banana','strawberry'])
print(np.sort(arr))

['apple' 'banana' 'pineapple' 'strawberry']


21/6/23

In [87]:
arr = np.array([-5,65,70,-7550,20,300,30])

print(arr[0:2])

[-5 65]


In [88]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43]])
print(mat)
print(mat[1,1])
print(mat[0,4])

[[10 20 21 22 25]
 [30 40 41 42 43]]
40
25


In [89]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43],[12,13,14,15,43]])
print(mat[0,1])
print(mat[1:3])

20
[[30 40 41 42 43]
 [12 13 14 15 43]]


In [90]:
mat=np.array([  [[21,22,23],[24,25,26]] , [[34,35,36],[31,32,33]] ] )        #3Dimensional
print(mat)
print("value:",mat[1,0,0])
print("value:",mat[1,1,0])
print(mat[1,1,1:3])

[[[21 22 23]
  [24 25 26]]

 [[34 35 36]
  [31 32 33]]]
value: 34
value: 31
[32 33]


In [91]:
arr=np.array([1,2,3,4,5,6])

print(arr[1:5:2])

[2 4]


In [92]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


Searching in array

numpy.where()
<>
numpy.searchsorted()

In [93]:
arr=np.array([1,2,3,4,5,6,7,8])

val=np.where(arr%4==0)
print(val)


(array([3, 7], dtype=int64),)


In [94]:
arr=np.array([2,50,23,60,56,80])

val=np.where(arr%10==0)
print(val)

(array([1, 3, 5], dtype=int64),)


In [95]:
arr=np.array([0.4,0.5,0.7,0.8,0.9])

val=np.where(arr==0.7)
print(val)

(array([2], dtype=int64),)


In [96]:
arr=np.array(["'a'",'b','c','d','e','f'])

val=np.where(arr=='d')

print(val)

(array([3], dtype=int64),)
