Numpy 

In [1]:
import numpy as np 


filling arrays with auto elements

In [5]:
import numpy as np

arr = np.zeros(4)
print(arr)                  #return value is lidt

[0. 0. 0. 0.]


In [14]:
arr=np.ones((4,2))    #tuple
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
arr=np.arange(10,21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


In [19]:
arr=np.arange(4)
print(arr)

[0 1 2 3]


In [21]:
arr=np.arange(2,14,2)
print(arr)

[ 2  4  6  8 10 12]


sorting array

In [30]:
arr=np.array([2,1,5,3,7,4,6,8])

print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [33]:
arr=np.array(['apple','pineapple','banana'])
print(np.sort(arr))

['apple' 'banana' 'pineapple']
